import NextAuthSession from "@/components/NextAuthSession";
import ThemeRegistry from "@/components/ThemeRegistry";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <NextAuthSession session={session}>
          <ThemeRegistry>{children}</ThemeRegistry>
        </NextAuthSession>
      </body>
    </html>
  );
}
